//
//  KamuSettingsPresenter.swift
//  TWKamu
//
//  Created by Guilherme Coelho on 22/08/18.
//  Copyright (c) 2018 ThoughtWorks. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class KamuSettingsPresenter {
  
  // MARK: - Private properties -
  
  private unowned let view: KamuSettingsViewInterface
  private let wireframe: KamuSettingsWireframeInterface
  
  // MARK: - Lifecycle -
  
  init(wireframe: KamuSettingsWireframeInterface,
       view: KamuSettingsViewInterface) {
    self.wireframe = wireframe
    self.view = view
  }
}

// MARK: - Extensions -

extension KamuSettingsPresenter: KamuSettingsPresenterInterface {
}
