//
//  LibrariesPresenter.swift
//  TWKamu
//
//  Created by Guilherme Coelho on 13/08/18.
//  Copyright (c) 2018 ThoughtWorks. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LibrariesPresenter {
  
  // MARK: - Private properties -
  
  private unowned let view: LibrariesViewInterface
  private let wireframe: LibrariesWireframeInterface
  
  // MARK: - Lifecycle -
  
  init(wireframe: LibrariesWireframeInterface,
       view: LibrariesViewInterface) {
    self.wireframe = wireframe
    self.view = view
  }
}

// MARK: - Extensions -

extension LibrariesPresenter: LibrariesPresenterInterface {
}
