//
//  KamuBookDetailPresenter.swift
//  TWKamu
//
//  Created by Guilherme Coelho on 23/08/18.
//  Copyright (c) 2018 ThoughtWorks. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class KamuBookDetailPresenter {
  
  // MARK: - Private properties -
  
  private unowned let view: KamuBookDetailViewInterface
  private let wireframe: KamuBookDetailWireframeInterface
  
  private let book: KamuBook
  
  // MARK: - Lifecycle -
  
  init(wireframe: KamuBookDetailWireframeInterface,
       view: KamuBookDetailViewInterface,
       book: KamuBook) {
    
    self.wireframe = wireframe
    self.view = view
    self.book = book

  }
}

// MARK: - Extensions -

extension KamuBookDetailPresenter: KamuBookDetailPresenterInterface {
}
