platform :ios, '10.0'

target 'TWKamu' do
  
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'

  # Pods for TWKamu
  target 'TWKamuTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
