//
//  HomePresenter.swift
//  TWKamu
//
//  Created by Guilherme Coelho on 13/08/18.
//  Copyright (c) 2018 ThoughtWorks. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomePresenter {
  
  // MARK: - Private properties -
  
  private unowned let view: HomeViewInterface
  private let wireframe: HomeWireframeInterface
  
  // MARK: - Lifecycle -
  
  init(wireframe: HomeWireframeInterface,
       view: HomeViewInterface) {
    self.wireframe = wireframe
    self.view = view
  }
}

// MARK: - Extensions -

extension HomePresenter: HomePresenterInterface {
  
  func startIsPressed() {
    wireframe.navigate(to: .goToLibraries)
  }
  
  func configureWelcomeLabel() -> String {
    return KamuStrings.Labels.home_welcome
  }
  
  func configureStartButton() -> String {
    return KamuStrings.Buttons.login
  }
  
}
