//
//  KamuExplorePresenter.swift
//  TWKamu
//
//  Created by Guilherme Coelho on 21/08/18.
//  Copyright (c) 2018 ThoughtWorks. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class KamuExplorePresenter {
  
  // MARK: - Private properties -
  
  private unowned let view: KamuExploreViewInterface
  private let wireframe: KamuExploreWireframeInterface
  
  // MARK: - Lifecycle -
  
  init(wireframe: KamuExploreWireframeInterface,
       view: KamuExploreViewInterface) {
    self.wireframe = wireframe
    self.view = view
  }
}

// MARK: - Extensions -

extension KamuExplorePresenter: KamuExplorePresenterInterface {
}
